In [2]:
import pandas as pd

- Read from a csv file and convert to a dataframe

In [5]:
csv_df = pd.read_csv('random.csv')

- Show the first 5 items in a dataframe

In [6]:
csv_df.head()

,id,first_name,last_name,email,gender,ip_address
0,1,Bernardine,Sappell,bsappell0@cornell.edu,Female,8.163.204.26
1,2,Lilah,Jewitt,ljewitt1@prweb.com,Female,244.233.34.193
2,3,Reena,Leward,rleward2@webnode.com,Female,154.35.205.179
3,4,Corrinne,Betty,cbetty3@creativecommons.org,Female,176.111.219.240
4,5,Hashim,Boagey,hboagey4@discuz.net,Genderfluid,219.92.255.147

- Read from a json file and use tail to show last 5 items

In [8]:
json_df = pd.read_json('users.json')
json_df.tail()

,id,first_name,last_name,email,gender,ip_address
995,996,Carey,Larwell,clarwellrn@jigsy.com,Male,132.86.101.110
996,997,Huntington,Medler,hmedlerro@google.co.jp,Male,249.246.100.13
997,998,Marjy,Greengrass,mgreengrassrp@ycombinator.com,Female,221.252.246.19
998,999,Filberte,Picard,fpicardrq@dion.ne.jp,Male,125.139.245.2
999,1000,Kiley,Jerram,kjerramrr@springer.com,Polygender,111.210.31.247

- To list the columns on a dataframe

In [18]:
csv_df.columns

Index(['id', 'first_name', 'last_name', 'email', 'gender', 'ip_address'], dtype='object')

- show the number of rows and columns

In [10]:
csv_df.shape

(1000, 6)

- shows summary statistocs for numerical columns

In [12]:
csv_df.describe()

                id
count  1000.000000
mean    500.500000
std     288.819436
min       1.000000
25%     250.750000
50%     500.500000
75%     750.250000
max    1000.000000

In [23]:
csv_df.describe

<bound method NDFrame.describe of        id  first_name last_name                        email       gender  \
0       1  Bernardine   Sappell        bsappell0@cornell.edu       Female
1       2       Lilah    Jewitt           ljewitt1@prweb.com       Female
2       3       Reena    Leward         rleward2@webnode.com       Female
3       4    Corrinne     Betty  cbetty3@creativecommons.org       Female
4       5      Hashim    Boagey          hboagey4@discuz.net  Genderfluid
..    ...         ...       ...                          ...          ...
995   996      Jasper   Purveys            jpurveysrn@w3.org         Male
996   997      Aileen     Bibby          abibbyro@amazon.com   Polygender
997   998   Alexander   Tomovic        atomovicrp@meetup.com         Male
998   999    Rayshell     Ribou         rribourq@youtube.com   Non-binary
999  1000      Kelley   Giraldo        kgiraldorr@boston.com       Female

          ip_address           full_name
0       8.163.204.26  Bernardine Sappell
1     244.233.34.193        Lilah Jewitt
2     154.35.205.179        Reena Leward
3    176.111.219.240      Corrinne Betty
4     219.92.255.147       Hashim Boagey
..               ...                 ...
995   255.25.219.102      Jasper Purveys
996  138.203.215.143        Aileen Bibby
997    241.47.237.85   Alexander Tomovic
998   185.101.16.170      Rayshell Ribou
999    57.225.41.213      Kelley Giraldo

[1000 rows x 7 columns]>

In [16]:
csv_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          1000 non-null   int64
 1   first_name  1000 non-null   object
 2   last_name   1000 non-null   object
 3   email       1000 non-null   object
 4   gender      1000 non-null   object
 5   ip_address  1000 non-null   object
dtypes: int64(1), object(5)
memory usage: 47.0+ KB

In [19]:
csv_df[['first_name', 'last_name']]

     first_name last_name
0    Bernardine   Sappell
1         Lilah    Jewitt
2         Reena    Leward
3      Corrinne     Betty
4        Hashim    Boagey
..          ...       ...
995      Jasper   Purveys
996      Aileen     Bibby
997   Alexander   Tomovic
998    Rayshell     Ribou
999      Kelley   Giraldo

[1000 rows x 2 columns]

In [22]:
csv_df['full_name'] = csv_df['first_name'] + ' ' +  csv_df['last_name'] 
csv_df.tail()

,id,first_name,last_name,email,gender,ip_address,full_name
995,996,Jasper,Purveys,jpurveysrn@w3.org,Male,255.25.219.102,Jasper Purveys
996,997,Aileen,Bibby,abibbyro@amazon.com,Polygender,138.203.215.143,Aileen Bibby
997,998,Alexander,Tomovic,atomovicrp@meetup.com,Male,241.47.237.85,Alexander Tomovic
998,999,Rayshell,Ribou,rribourq@youtube.com,Non-binary,185.101.16.170,Rayshell Ribou
999,1000,Kelley,Giraldo,kgiraldorr@boston.com,Female,57.225.41.213,Kelley Giraldo